const vacancyBlockData = [
  {
    title: "Junior Frontend-разработчик",
    cash: "от 30 000 Р",
    company: "Интернет Люди",
    city: "Ярославль",
    exp: "Опыт от 1 года до 3 лет",
  },
  {
    title: "Middle Frontend React разработчик",
    cash: "120 000 - 180 000 Р",
    company: "Torgbox",
    city: "Красноярск",
    exp: "Опыт от 6 лет",
  },
  {
    title: "Frontend-разработчик на JavaScript",
    cash: "80 000 - 120 000 Р",
    company: "IT-парк Питерский мостик",
    city: "Красноярск",
    exp: "Опыт от 1 года до 3 лет",
  },
  {
    title: "Frontend-разработчик (Angular)",
    cash: "180 000 - 280 000 Р",
    company: "Клируэй Текнолоджис",
    city: "Москва",
    exp: "Опыт от 3 года до 6 лет",
  },
  {
    title: "Frontend-разработчик",
    cash: "50 000 - 150 000 Р",
    company: "ООО Омегасофтвер Рус",
    city: "Ижевск",
    exp: "Без опыта",
  },
  {
    title: "Frontend-разработчик",
    cash: "от 80 000 Р",
    company: "ООО Эмфи",
    city: "Москва",
    exp: "Опыт от 1 года до 3 лет",
  },
  {
    title: "Junior Frontend-разработчик",
    cash: "от 30 000 Р",
    company: "Интернет Люди",
    city: "Ярославль",
    exp: "Опыт от 1 года до 3 лет",
  },
  {
    title: "Middle Frontend React разработчик",
    cash: "120 000 - 180 000 Р",
    company: "Torgbox",
    city: "Красноярск",
    exp: "Опыт от 6 лет",
  },
  {
    title: "Frontend-разработчик",
    cash: "80 000 - 120 000 Р",
    company: "IT-парк Питерский мостик",
    city: "Красноярск",
    exp: "Опыт от 1 года до 3 лет",
  },
  {
    title: "Frontend-разработчик",
    cash: "180 000 - 280 000 Р",
    company: "Клируэй Текнолоджис",
    city: "Москва",
    exp: "Опыт от 3 года до 6 лет",
  },
  {
    title: "Frontend-разработчик",
    cash: "50 000 - 150 000 Р",
    company: "ООО Омегасофтвер Рус",
    city: "Ижевск",
    exp: "Без опыта",
  },
  {
    title: "Frontend-разработчик",
    cash: "от 80 000 Р",
    company: "ООО Эмфи",
    city: "Москва",
    exp: "Опыт от 1 года до 3 лет",
  },
];

export default vacancyBlockData;
